language: python

sudo: false

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - python setup.py install
  - python setup.py develop
  - pip install flake8
  - pip install pytest  # fixes a dependency problem

script:
  - flake8 --statistics --count setup.py djcron_agent
  - python setup.py test

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change
